language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
script:
- ./gradlew clean build --stacktrace
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
env:
  global:
  - secure: 5HGPSQCOqb0ixRmvo+eONvyMn3dH8N4+P9LCCs72dajCu4pEgOd4hMnxVhq9THsYVl58LH0pB2eihaLDsGncf0ma4kH3rgr3X55TaRhhrxOjPHgfLEEkKf93qohWbdE6JkEp6H1iwHCotKkGCltLqjcy9EC3jO+3d1X3AjywWr1qQ1kiwxx9yuZpMGMA7Gdl9HaX/enHODdyOKu+XYT1/LUsX5LZyBy1MwdadL2Dr6zXFgy6f8wzHKP+Zl07CbeWcqbb+8XnwQiNejAj7XFl0IHyrLpSUDyzTDfuIQRefnHd92K5bznhlFhyVLZTJf/HuUaHOFEgj5hWH88Cfjyd3o4DSqttsKsQjGL0uH7cqwaWiyAhWoxWYZ41n5Q8TU8uZqc4OpYXE8WZqTasx4U0On3XGDIsZAEzM5lS01gLny5y0rpTaiNMFtq/1bPxHq1zDMwpyVzRUnI+uRa8S6oD2OJGlGbAPpUwFPtbUTUKqAlIfo3JILT9GImN0A4JXMd85uQUoSlt2VpEVoCSyvPNxZJ65O15ktyP6eRAWaCYsqmmvpxewH5SveS9SetJvcRnLdkO7AbbPI2929VmGSOpAT3OjPNuhCP010mZxXVOiTljObgAtEDpOcwj18bQ0566fdH5swdKyuEO26bGxL3WQxrVArK17KIkaWplwG8/qVc=
  - secure: YT9dEjpKGMyIQAJ2Wsc8UekmwALF5whpFPl/ZgLbsIqNQhmdlIffm8SIlANVTc6eDdMstLzE9MFRYbFJ88wWi4w06tpbAsznMS9yE8JBGH+InVr03yFeXTayWV8GgdH1D9PDbRK3zNIT5qrTLz37GoxnH9jx7UFh8PnmNi00467nZcJN6X3bRWkosmkl8j9zdO1sB0UScYXxzF2yQ/2BYPSlN7YrxSrba5Y9t2/SJ+Ti/vDNty0NAhmdS42M6Cb0oQcf89fJw9yQ4T4zoynbKy1cQcdarEQA5F0cdck8GYRqvVMoY0UYmMHtf7GDJqX6QsqUdnTCFsBmmaIvK3YhJKhaMx64X82X2nWN8IqiY+5QQTv11ZTGo/h/XOgk9L7QOADuq0UCgibMIfApcV1mWDmEALwHGkYNeoqTOx7j8PznIHbO0kamNOsTQjq798wYBh60RSQVMDWL64p26AMNL0CuLIm0yW+xtbSpzJgOYHnYg+ffXBxELz1RvyQhVl/iK0gYdA23yfOsW9qvDennQy4VlZlfsA65jZc1cYVN8hupZc45qCdFij+5qUTBu0/Y1NjUVgckQ5RNLIrHo2Enk+VSipJIRp087s25QuaDQVpObJ2NBkaNi1T8Pbs4CMqa1dmO8QicBdHH55I/XSwsX75yZ5ycAwSsNCARYPD6fhw=
  - secure: CaqggGu9JCCoTrvHIGYvHMhw5kKD/mErZeKzmpFGrWbmaAC3h8QWLR/Zo0V+1saiyvZbO0xqXsBYJJub2yJL524N/1dojylimxz1ev3jsXStwV/gYWoaIsD8XMaP1G4VqJ79tafLOUSNb2YpzKgDgfal//mTHgehsjB5WmLJLqXzA/rVv9frAJoy46mq/A6wsK2om3TfrKzivLp0Qx2yMmpzWXKVJQVBv1Z8hoTNr7kiOy6tC5Fn9arI2SDlcxKEiYdknYBu36tsf7ceb3rawThki/Ix9GufzNlSx3gOFXOjdxKmKLtBdmoXrEMHzr1xwzQ6rphelwwxYyJdHQbpy76EYlp9iwCZCQbn+DGKAxOPbE4QQRnsGAL/awWSQBvi9ZpAuAZZh1YO9MGtvPWxgS79pvXF42o7CxTsJD7skFfWyT+5nkN5v7SmwGYokyXgxXrn8v1fwUOpcSHL92Me9pzxp26G1+hJfSultHwW+bbmsOKm9vI94/zFh5RqZ5Bm39wqzbT1NMHxvN/c14CfTVcQxOhKepDkh+nBEkcq1RPGR4EOxYZVARM/e2V4NcXzeQOU9HWdGHYBCUjDbyBVrwF1Y/7ST5igiimCww2PNDBkuxkMn1gr8z6LKixAln2YrYA0vUsmZfPJmkOhxpF0daPrXRrs2iIUE71ZpD3fbfQ=
  - secure: OstjwrfQEHrPCkpwIBd3f9GdHmqWoX+GzKGnd3BRpZnJkOmMqz3aa/XkZXmj+qah7mFrM1KQzUj5qKKfD/pgB3l9T+XWMzC08a5JFyT8E/qHXZMCxD0Lx3FLUve8wnzofFbfJYdezV/515pYL2ClC2fkbRY5shGEJ0IH0e6QwzlTNGgJ8E6rho8NWot4b7j4j9ZwTyRcYw2xUWQEDseFXdquLvuCy2B34EDqbR9A5+bcVwUmctqyEICzZ2ANxofw2+jZqAkzolMWPuzOqEshWC3WIwXzNW2vx0GRPPWR+t4l0wlcJeHueKcDs8sjTmoYHFEDJxKjCCegv96gXc7jQ+K/MBCLABBwnv1xRE8OtRBBjDW/UYbDbSHsBof5vezqzn4oyaWRxdDk4kujbMUotvquCzJWXXBqmpK2CzeHbq/aucKpJZRVQxQMYRK2yxyFRwZNaRcJpq1CCMW6nykzwR69huZ9uRdydSW9MBwWE+RKXOJ0ydRJj6H7xIaEw5n6fZbTSYsKx4cC+awPV179zON+hN+crDTBZosgSQIMspRB7byz09/WZdhGG8u5RtvQ5J2KOPMXOHA8LDpQUOLkK1h3xEKmStcbA2zU4yJKeVXuTm8vsoDF4m9WOW6UFxNo5Z4nymR07nNjyutzu5I1aL/yVyiZuVc5agJOIFCmJ+0=
